from django.core.management.base import BaseCommand, CommandError
from logs.models import Trainee, Attending, Procedure, Procedure_Code, Patient
import csv
from datetime import datetime
from time import time

MRN = 4
RAD_1 = 5
RAD_2 = 6
PROC_DESC = 20
START_TIME = 9
END_TIME = 10
READ_TIME = 11
SIGN_TIME = 12
ADDEND_TIME = 13
TECH = 14
LOCATION = 15
DEPT = 16
FLUORO_TIME = 17

class Command(BaseCommand):
	help = 'loads syngo data from a comma delimited CSV generated by Syngo people'
	
	def add_arguments(self, parser):
		parser.add_argument('filename')

	def calcDuration(self, start_time, end_time):
		return (datetime.strptime(end_time, "%b %d, %Y  %I:%M%p") 
		- datetime.strptime(start_time, "%b %d, %Y  %I:%M%p"))

	def handle(self, *args, **options):
		with open(options['filename'], 'rb') as f:
			procedure = None
			procedure_description = ""
			index = 0
			mrn = 0
			reader = csv.reader(f, delimiter='\t')
			for row in reader:	
				if len(row) > 1 and row[START_TIME] and row[RAD_1]:
					procedure, created = Procedure.objects.get_or_create(start_time = datetime.strptime(row[START_TIME], "%b %d, %Y  %I:%M%p"), mrn = '00000', duration=self.calcDuration( row[START_TIME], row[END_TIME]))
					if created:
						procedure.attending, created = Attending.objects.get_or_create(abbrev_name = row[RAD_1]);
						if row[RAD_2]: 
							procedure.trainee, created = Trainee.objects.get_or_create(abbrev_name = row[RAD_2]);
						if row[TECH]: procedure.tech = row[TECH];
						if row[LOCATION]: procedure.location = row[LOCATION];
						if row[DEPT]: procedure.department = row[DEPT];
						if row[FLUORO_TIME]: procedure.fluoro_time = row[FLUORO_TIME];
						if row[READ_TIME]: procedure.read_time = row[READ_TIME];
						if row[SIGN_TIME]: procedure.sign_time = row[SIGN_TIME];
						prc_desc = row[PROC_DESC].partition(' ')
						if prc_desc[0] == "IVRFUin": prc_desc = prc_desc[2].partition(' ')
						procedure_code = Procedure_Code.objects.create(code = prc_desc[0], description = prc_desc[2])
						procedure_code.procedure = procedure
						procedure_code.save()
						procedure.save()
						mrn = row[MRN]
					elif mrn == row[MRN]:
						prc_desc = row[PROC_DESC].partition(' ')
						procedure_code = Procedure_Code(code = prc_desc[0], description = prc_desc[2])
						procedure_code.procedure = procedure
						procedure_code.save()				
